#!/usr/bin/env bash
set -euo pipefail

source stuff/colours.sh

__FIGLET="$(command -v figlet || true)"
__LOLCAT="$(command -v lolcat || true)"

clear
echo ""
if [[ "${__FIGLET}" == "" ]] ; then
  echo "  CoP Demo!"
else
  if [[ "${__LOLCAT}" == "" ]] ; then
    figlet "  CoP Demo!"
  else
    figlet "  CoP Demo!" | lolcat
  fi
fi
echo ""
echo "     Workstation tooling with Ansible and venv!"
echo ""
echo ""
