#!/usr/bin/env bash
set -euo pipefail
readonly red="$(tput setaf 1)$(tput bold)"
readonly green="$(tput setaf 2)$(tput bold)"
readonly blue="$(tput setaf 6)$(tput bold)"
readonly purple="$(tput setaf 5)$(tput bold)"
readonly reset="$(tput sgr0)"

clear
echo ""
echo "[${USER}@$(hostname) $(basename $(pwd))]$ cat ${green}stuff/new.yml${reset}"
echo ""
cat stuff/new.yml
echo ""
