#!/usr/bin/env bash
set -euo pipefail

source stuff/colours.sh

clear
echo ""
echo "[${USER}@$(hostname) $(basename $(pwd))]$ diff -u --color ${blue}stuff/new.yml ${green}stuff/old.yml${reset}"
echo ""
diff -u --color stuff/new.yml stuff/old.yml
echo ""
