#!/usr/bin/env bash
set -euo pipefail

source stuff/colours.sh

clear
echo ""
echo "[${USER}@$(hostname) $(basename $(pwd))]$ cat ${green}$(command -v ansible)${reset}"
echo ""
cat "$(command -v ansible)"
echo ""
