#!/usr/bin/env bash
set -euo pipefail

source stuff/colours.sh

clear
echo "[${USER}@$(hostname) $(basename $(pwd))]$ ls -lh --color ${green}$(command -v terraform)${reset}*"
echo ""
ls -lh --color $(command -v terraform)*
echo ""
