#!/usr/bin/env bash
set -euo pipefail

source stuff/colours.sh

clear
echo ""
echo "[${USER}@$(hostname) $(basename $(pwd))]$ diff -u --color ${blue}stuff/old.yml ${green}stuff/new.yml${reset}"
echo ""
diff -u --color stuff/old.yml stuff/new.yml
echo ""
