---

- name: Create an all-in-one virtualenv
  hosts: workstation
  vars:
    venv_name: workspace
    venv_suffix: 1.0.0
    install_dir: "{{ ansible_user_dir }}/.virtualenvs/{{ venv_name }}-{{ venv_suffix }}"
    controller_ansible_version: 2.8.0
    controller_ansible_venv_name: "{{ venv_name }}"
    controller_ansible_venv_suffix: "{{ venv_suffix }}"
    controller_ansible_install_venv_helper: false
    controller_ansible_support_packages:
      - azure
    terraform_version: 0.11.8
    terraform_install_dir: "{{ install_dir }}/bin"
    molecule_version: 2.22.0
    molecule_venv_name: "{{ venv_name }}"
    molecule_venv_suffix: "{{ venv_suffix }}"
    molecule_install_venv_helper: false
    molecule_support_packages:
      - docker
      - lint
    azcli_version: 2.5.0
    azcli_venv_name: "{{ venv_name }}"
    azcli_venv_suffix: "{{ venv_suffix }}"
    azcli_install_venv_helper: false
    sshuttle_version: 0.78.5
    sshuttle_venv_name: "{{ venv_name }}"
    sshuttle_venv_suffix: "{{ venv_suffix }}"
    sshuttle_install_venv_helper: false
  roles:
    - xanmanning.controller
    - xanmanning.terraform
    - xanmanning.molecule
    - xanmanning.azurecli
    - xanmanning.sshuttle
