---

- name: xanmanning.controller
  version: v0.5.0
- name: xanmanning.terraform
  version: v0.1.5
- name: xanmanning.molecule
  version: v0.3.0
- name: xanmanning.azurecli
  version: v0.5.0
- name: xanmanning.sshuttle
  version: v0.3.1
